network.host: 0.0.0.0

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1

cluster.name: Crazw
node.name: MacBook

# https://github.com/hlstudio/bigdesk
http.cors.enabled: true
http.cors.allow-origin: "*"
